# Generated by Django 4.2.1 on 2023-06-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_rename_trainee_info_trainee_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee_list',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
