# Generated by Django 4.2.1 on 2023-06-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee_info',
            name='is_activ',
            field=models.BooleanField(default=True),
        ),
    ]
