# Generated by Django 4.2.1 on 2023-06-02 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trainee_info',
            new_name='trainee_list',
        ),
    ]
