# Generated by Django 4.2.1 on 2023-06-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_capacity',
            field=models.IntegerField(default=20),
        ),
    ]
