# Generated by Django 4.2.1 on 2023-06-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_trainee_info_is_activ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee_info',
            old_name='trainee_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='trainee_info',
            old_name='trainee_name',
            new_name='firstname',
        ),
    ]
